// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0WiK9J8Rojh1B22l9YX_uJaFcAqcLFI',
    appId: '1:413101648118:web:80c8a37acc175c607e64d7',
    messagingSenderId: '413101648118',
    projectId: 'map-ifpi',
    authDomain: 'map-ifpi.firebaseapp.com',
    storageBucket: 'map-ifpi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GyEevnh0d2ZCTFVQIGpicUdJWuOHCNk',
    appId: '1:413101648118:android:b9e87c0de50c510d7e64d7',
    messagingSenderId: '413101648118',
    projectId: 'map-ifpi',
    storageBucket: 'map-ifpi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4R7Aw38g3ngt5ay5jOR4N_X6x30es3CU',
    appId: '1:413101648118:ios:a06bbf66bb4215b07e64d7',
    messagingSenderId: '413101648118',
    projectId: 'map-ifpi',
    storageBucket: 'map-ifpi.appspot.com',
    iosClientId: '413101648118-vrbvafgcqsnunl478pv2va0q0t1ki5r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4R7Aw38g3ngt5ay5jOR4N_X6x30es3CU',
    appId: '1:413101648118:ios:a06bbf66bb4215b07e64d7',
    messagingSenderId: '413101648118',
    projectId: 'map-ifpi',
    storageBucket: 'map-ifpi.appspot.com',
    iosClientId: '413101648118-vrbvafgcqsnunl478pv2va0q0t1ki5r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.map',
  );
}
